# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

addSimplices <- function(x, y) {
    .Call('hclustPH_addSimplices', PACKAGE = 'hclustPH', x, y)
}

