# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

addList <- function(simplist_reps, simplist_adds) {
    .Call('hclustPH_addList', PACKAGE = 'hclustPH', simplist_reps, simplist_adds)
}

addSimplices <- function(x, y) {
    .Call('hclustPH_addSimplices', PACKAGE = 'hclustPH', x, y)
}

findEdges <- function(simps, d, n) {
    .Call('hclustPH_findEdges', PACKAGE = 'hclustPH', simps, d, n)
}

hclustIntermediate <- function(l, r) {
    .Call('hclustPH_hclustIntermediate', PACKAGE = 'hclustPH', l, r)
}

matSort <- function(X, n, d) {
    .Call('hclustPH_matSort', PACKAGE = 'hclustPH', X, n, d)
}

topsimps <- function(simplist) {
    .Call('hclustPH_topsimps', PACKAGE = 'hclustPH', simplist)
}

